pd_user:
    user_class: App\Entity\Account\User
    profile_class: App\Entity\Account\Profile
    group_class: App\Entity\Account\Group
    default_group: "%user_default_group%"
    login_redirect: '%user_login_redirect%'
    email_confirmation: "%user_email_confirmation%"
    welcome_email: "%user_welcome_email%"
    user_registration: "%user_registration%"
    template_path: 'Auth'
    resetting_request_time: 7200
    mail_sender_address: "%mail_sender_address%"
    mail_sender_name: "%mail_sender_name%"
    active_language: "%active_language%"
