parameters:
    ##
    # General Default Config
    ##
    head_title: 'TunInfoCrm'
    head_title1: 'TunInfoCrm'
    head_title_pattern: '&T - &P'

    head_description: ''
    head_description1: 'CRM TUNINFO Head Description'
    head_author1: 'FADI MATHLOUTHI '
    head_author: 'FADI MATHLOUTHI '
    head_keywords: 'TunInfoCrm'
    head_keywords1: 'TunInfoCrm'
    footer_copyright: 'TunInfoForYou CRM 2020'
    footer_copyright1: 'TunInfoForYou CRM 2020'
    default_locale: 'fr'
    default_country: 'TUN'
    default_locale1: 'fr'
    default_country1: 'TUN'
    site_logo: null
    default_image: null
    site_favicon: null

    ##
    # Email Default Config
    ##
    mail_disable_delivery: false
    mail_transport: null
    mail_host: 'f.mathlouthi8@gmail.com'
    mail_port: 465
    mail_username: 'f.mathlouthi8@gmail.com'
    mail_password: 'qglblojeilohvein'
    mail_timeout: 30
    mail_encryption: ssl
    mail_auth_mode: login
    mail_allow_self_signed: true
    mail_verify_peer: false
    mail_sender_address: 'f.mathlouthi8@gmail.com'
    mail_sender_name: 'TunInfoForYou CRM'
    mail_test_address: ''
    # Hidden
    mail_spool_type: memory
    mail_spool_dir: '%kernel.cache_dir%/swiftmailer/spool'
    mail_antiflood_threshold: 99
    mail_antiflood_sleep: 0
    mail_delivery_address: []

    ##
    # User Default Config
    ##
    user_registration: true
    user_default_group: null
    user_login_redirect: login_success
    user_logout_redirect: security_login
    user_email_confirmation: true
    user_welcome_email: true

    ##
    # Media Default Config
    ##
    media_library: gd
    media_optimize: 1
    media_max_width: 1028
    media_max_height: 768
    media_quality: 75
    media_watermark: text
    media_wm_image: null
    media_wm_image_position: null
    media_wm_image_x: null
    media_wm_image_y: null
    media_wm_font: ''
    media_wm_font_text: 'CRM TUNINFO'
    media_wm_font_size: '36'
    media_wm_font_color: '#445160'
    media_wm_font_align: 'center'
    media_wm_font_valign: 'middle'
    media_wm_font_x: '0.5'
    media_wm_font_y: '0.5'
    media_wm_font_angle: 45

    ##
    # Contact Default Config
    ##
    contact_email: 'info@example.com'
    contact_phone: ''
    contact_mobile_phone: ''
    contact_fax_number: ''
    contact_address: ''
    contact_facebook: ''
    contact_twitter: ''
    contact_google: ''
    contact_youtube: ''
    contact_linkedin: ''
    contact_whatsapp: null

    ##
    # Core Default Config
    ##
    active_language: [en,fr]
    list_count: 30
    remember_time: 604800 # 1 Week - 1 Month -> 2592000
    twig_cache: '%kernel.cache_dir%/twig'
    admin_allow_ips: "['']"
    auth_allow_ips: "['']"
    # Hidden
    upload_dir: '%kernel.project_dir%/public/uploads/'
