##
# Authorization Routing
##
authorization:
    resource: "@PdUserBundle/Resources/config/routing.yaml"
    prefix: 'auth'
    condition:  "%auth_allow_ips% == [''] ?: (request.getClientIp() in %auth_allow_ips%)"

##
# Admin Controller Routing
##
admin:
    resource: ../src/Controller/
    type: annotation
    prefix: 'admin'
    name_prefix: 'admin_'
    condition:  "%admin_allow_ips% == [''] ?: (request.getClientIp() in %admin_allow_ips%)"
admin_mailer:
    resource: "@PdMailerBundle/Resources/config/routing.yaml"
    prefix: 'admin'
    condition:  "%admin_allow_ips% == [''] ?: (request.getClientIp() in %admin_allow_ips%)"
admin_widget:
    resource: "@PdWidgetBundle/Resources/config/routing.yml"
    prefix: 'admin'
    condition:  "%admin_allow_ips% == [''] ?: (request.getClientIp() in %admin_allow_ips%)"

##
# Home
##
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: homepage.html.twig
